updates:
- assignees:
  - gaocegege
  - johnugeorge
  - richardsliu
  - terrytangyuan
  - jeffwan
  directory: .
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  schedule:
    interval: daily
version: 2
