language: go

go:
  - "1.13"

go_import_path: github.com/kubeflow/common

install:
  # get coveralls.io support
  - go get github.com/mattn/goveralls
  # Install golangci-lint
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.7

script:
  - ./hack/verify-codegen.sh
  - go build ./...
  - go fmt ./...
  - golangci-lint run --config=linter_config.yaml ./...
  # Here we run all tests in pkg and we have to use `-ignore`
  # since goveralls uses `filepath.Match` to match ignore files
  # and it does not support patterns like `**`.
  - goveralls -service=travis-ci -v -package ./... -ignore "test_job/client/*/*.go,test_job/client/*/*/*.go,test_job/client/*/*/*/*.go,test_job/client/*/*/*/*/*.go,test_job/client/*/*/*/*/*/*.go,test_job/client/*/*/*/*/*/*/*.go,test_job/testutil/*.go,test_job/*/*/*/zz_generated.*.go,test_job/*/*/*/*_generated.go,pkg/apis/common/*/zz_generated.*.go,pkg/apis/common/*/*_generated.go"
